### ISSUE TITLE
Problem with instructions...no bin

### ISSUE THREAD

**Issue by VoR0220** [bitpay/bitcore-wallet#34]
So I've been playing around with this here. Very interesting stuff you have going on here. 

But here's the problem. The command cd bin returns nothing once we've created bws. I even went and looked in my /usr/bin files and there is no wallet command. Perhaps there was something else you meant to put down for the instructions? In addition, trying to run the start script again gives me this error: 

    vor0220@vor0220-ubuntu:~/BitcorePlayground/bws$ node start
    module.js:340
        throw err;
          ^
    Error: Cannot find module '/home/vor0220/BitcorePlayground/bws/start'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:503:10)
    at startup (node.js:132:16)
    at node.js:817:3

**Comment by matiu** [comment]
I believe you wanted to send this issue to bitcore-wallet-service repo, no bitcore-wallet.

Also note that the command is `npm start` (no node start)
