### ISSUE TITLE
Can't be joined by Copay wallet (Version Problem)

### ISSUE THREAD

**Issue by bitalias** [bitpay/bitcore-wallet#36]
Hi,

I created a 2-3 wallet using bitcore-wallet 0.0.7. Tried to join it with Copay wallet 1.2.5 but following error appears:
'Could not join wallet: The wallet you are trying to join was created with an older version of the client app.'

Any help appreciated!

**Comment by matiu** [comment]
Hey, we need to update bitcore-wallet-client dependency at bitcore-wallet.
We will try to fix it ASAP.



On Mon, Sep 28, 2015 at 8:23 AM, bitalias <notifications@github.com> wrote:

> Hi,
>
> I created a 2-3 wallet using bitcore-wallet 0.0.7. Tried to join it with
> Copay wallet 1.2.5 but following error appears:
> 'Could not join wallet: The wallet you are trying to join was created with
> an older version of the client app.'
>
> Any help appreciated!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet/issues/36>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
Fixed at @0.6.0

thanks for the report.
