### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by tomtruitt** [bitpay/bitcore-wallet#48]
not an issue just a question, and please forgive my ignorance...

do i need to run a full node with BWS installed to run bitcore-wallet? it's looking like $160 a month with digital ocean for enough ssd to run a full node... or can it talk to a bitpay bitcore node with BWS?

**Comment by tomtruitt** [comment]
or does it just need to talk to BWS which could be run by a third party like bitpay for example

**Comment by isocolsky** [comment]
Bitcore-wallet is the command line equivalent of Copay. It will talk to the BWS server of your choice.

**Comment by tomtruitt** [comment]
right but i mean are there public servers? or do i have to run my own? the server needs a full node, bitcore-node, correct?

**Comment by tomtruitt** [comment]
I mean obviously copay didn't require full node so it talks to a BWS somewhere
