### ISSUE TITLE
!! Error: WALLET_BUSY: Wallet is busy, try later

### ISSUE THREAD

**Issue by Shashwat78** [bitpay/bitcore-wallet#72]
i tried this commend today ....

./wallet create  'my wallet' 2-2 -t

it gives me error but this same command worked  2 day before 

!! Error: WALLET_BUSY: Wallet is busy, try later

Why This happening ??

**Comment by Shashwat78** [comment]
any Help ??

**Comment by matiu** [comment]
The issue should be fixed now. There was a problem in our infrastructure. thanks for your patience.
